name: tripsafe
description: TripSafe mobile app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.5.6
  maplibre_gl: ^0.17.0
  geolocator: ^10.1.0
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  uuid: ^4.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/hi.json
    - assets/chatbot/en.json
    - assets/chatbot/hi.json
